name: show-directory
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
      - run: make setup
      - run: make test
      - run: make lint
      - run: make say-hello